name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

permissions:
  contents: write  # Needed for deploying to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Checkout latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 — Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3 — Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4 — Build the React app
      - name: Build project
        run: npm run build

      # Step 5 — Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
